---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-chat-react
  labels:
    app: react-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:
      - name: react-container
        image: atse2/quickchatreact:tagversion
        ports:
        - containerPort: 4002
