---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-chat-react
  labels:
    app: react-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:
      - name: react-container
        image: atse2/quickchatreact:30
        imagePullPolicy: Always
        ports:
        - containerPort: 4002

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "quick-chat-react-service"
  namespace: "default"
  labels:
    app: "react-service"
    app.kubernetes.io/managed-by: "graphite-jenkins-gke"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4002
  selector:
    app: "react-service"
  type: "LoadBalancer"
  loadBalancerIP: ""