---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-chat-auth
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: atse2/quickchatauth:tagversion
        ports:
        - containerPort: 4002