---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-chat-auth
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: atse2/quickchatauth:tagversion
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: my-secret-volume
          mountPath: /secrets
          readOnly: true
      volumes:
        - name: my-secret-volume
          secret:
            secretName: quick-chat-secret
