---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "quick-chat-auth-service"
  namespace: "default"
  labels:
    app: "auth-service"
    app.kubernetes.io/managed-by: "graphite-jenkins-gke"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: "auth-service"
  type: "LoadBalancer"
  loadBalancerIP: ""